server:
  port: 9092


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url: http://localhost:8761/eureka
  instance:
    hostname: localhost

spring:
  application:
    name: USER-SERVICE